---
kind: pipeline
name: checks

trigger:
  event:
    exclude:
      - pull_request
      - tag

steps:
- name: checks
  image: picons/picons
  pull: always
  commands:
    - ./resources/tools/check-index.sh ./build-source srp
    - ./resources/tools/check-index.sh ./build-source snp
    - ./resources/tools/check-logos.sh ./build-source/logos

---
kind: pipeline
name: snp

trigger:
  event:
    - tag

steps:
- name: build
  image: picons/picons
  pull: always
  commands:
    - ./2-build-picons.sh snp-full

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
      - build-output/binaries-snp-full/*

---
kind: pipeline
name: srp

trigger:
  event:
    - tag

steps:
- name: build
  image: picons/picons
  pull: always
  commands:
    - ./2-build-picons.sh srp-full

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
      - build-output/binaries-srp-full/*
